### ISSUE TITLE
API to test batched writes

### ISSUE THREAD

**Issue by SamyPesse** [GitbookIO/expect-firestore#9]
This module is missing an API to test batched writes.

```js
await database.canCommit([
   firebase.Batch.set('users/userA', { .. }),
   firebase.Batch.delete('users/userA')
])
```

The goal is to have an API that match the firestore naming as much as possible:

- `batch.commit` -> `database.canCommit(batch: Array<firestore.Batch.Operation>)`
- `batch.set` -> `firestore.Batch.set(path: string, value: any)`
- `batch.delete ` -> `firestore.Batch.delete(path: string)`
- `batch.update ` -> `firestore.Batch.update(path: string, data: Object)`

The main blocker is that the Firestore rules API doesn't seem to support batch updates. Can you confirm @samtstern ?

**Comment by SamyPesse** [comment]
> It does not enforce the limit on max number of get() or exists() calls.

Ok, it may not be an issue since it can also be done internally by `expect-firestore` by checking the `functionCalls` in the API result.

I'm a bit worried that this restriction may impact us, so I want to have it tested instead of crashing in production.

On another matter: it's kind of crazy that Firebase bill the `get`, `getAfter` calls in the rules, it means that the real cost for a client operation is multiplied by the number of calls.  
I think it'll push your users to build less secure application so that they don't have to pay more. Security should not be a priced feature.  
Why not define a price where the first 5 get/getAfter are free, and after that there is a price per call ?

> It will not understand special things like server timestamps (actually have not tried this, but I bet)

I don't think we were using the equivalent in the RTDB, so it should not be an issue for us right now.


> It is not batch or transaction aware

Yes, the `getAfter` can be emulated by this module 👍 

But my main question is about the payload structure to describe a batch write. The [Google doc](https://docs.google.com/document/d/1rc_S5RrnxbEUezVN6uwLFNdttdeZ1o9ugQC_UarXRFI/edit) showcases a GET, I'm playing to make it work with UPDATE/CREATE, but I don't know how batch writes can be described in the payload.

**Comment by SamyPesse** [comment]
> We plan to raise the limits here pretty soon, and to raise them high enough that developers won't have to care unless they're doing something really crazy.

Good news 🎉 

> The rules engine tries pretty hard to not perform any billable actions when it can optimize them away, both to minimize charges to you and to minimize CPU/Network cost of rules to us. If you're seeing a significant percentage of your Firestore cost go to get() from rules, I'd love to discuss why. We have not heard much negative feedback on that point.

Ok, sorry I was probably anticipating the issue. We didn't deployed anything using Firestore yet, but we got a bit worried when we saw that the price will vary with our security rules.

> For a batched write with n documents, you will need to do n rules test invocations each with n-1 mocked getAfter() calls to represent the other documents in the batch.
> That pretty closely mirrors what happens in production, we execute the rules once per document action.

I'm gonna implement it in #10 👷

**Comment by samtstern** [comment]
Nice!

Just some more comments on pricing, rules document access will add a small, near-constant price increase to each request rather than a "multiplier" in most use cases.

For example, let's say your rules invoke `get()` on three unique documents.

  * If your primary data access pattern is a single-document `get()` then you will pay for 1 + 3 read operations, one from your client and one from rules.  In this case you're right, it seems to multiply the cost of reading data.
  * If you're writing a document, you'll be charged for one write operation and 3 read operations.  However writes are already 3x as expensive as reads so this is the same price as two write operations.
  * If you're doing a query that returns 100 documents, the rules are only checked once.  Rules only allows queries when it is sure, before checking any data, that all possible results will be allowed.  So in this case a successful query will cost 100 + 3 read operations.  In this case you can see how that's not going to be a big deal in pricing.

If you notice that your primary access pattern is a single-document `get()` that requires reading many other documents in rules, it's a good sign that your data structure is too relational and not well optimized for a NoSQL database like Cloud Firestore.  The usual solution here is to duplicate some data to optimize your read patterns.

I hope that makes sense!

**Comment by SamyPesse** [comment]
Yes it makes sense 👍 

Another worry: The payload sent to Google API will probably be huge, especially for batch write (where the functions mocked are relative to each test, and a document needs to be mocked twice for `getAfter` and `get`).

The formula will be:

```
PAYLOAD_SIZE = (NUMBER_OF_DOCS * 2) * OPERATIONS_IN_BATCH
```

At GitBook, we are testing with an important number of mocked documents; and we have more than 1000 tests; it means that will be sending a lot of data to Google API.

It'll be better if the payload accept some function mocks that are global to all tests.

Also on another matter, since this API seems pretty basic and not depending on Google secret sauce, why not open source the CEL evaluator ?  
So that it can be executed locally and avoid sending all of these requests to Google. The language spec is already open source (https://github.com/google/cel-spec), and it could help more people build tooling around it.

**Comment by samtstern** [comment]
> The payload sent to Google API will probably be huge, especially for batch write (where the functions mocked are relative to each test, and a document needs to be mocked twice for getAfter and get).

I have given the feedback that we should make the testing API accept something like a `data` param that's a JSON data blob similar to what `expect-firestore` uses.  Ideally the API would do a lot of these boilerplate mocks automatically.

> and we have more than 1000 tests; it means that will be sending a lot of data to Google API.

Yes that's a bad limitation of this API.  I can't say too much here but I can tell you we are working on introducing much better local testing tools for both Firestore and Rules.

> Also on another matter, since this API seems pretty basic and not depending on Google secret sauce, why not open source the CEL evaluator ?

As far as I am aware this is one of the CEL team's goals but I am not sure how far along.  It's also one of those things that may not be as useful as you imagine since CEL will never really know about the service-specific details of Firestore.

<hr />

I wish I had better answers for these great points!  At the very least, you are definitely being heard over here and for many of us, making Rules a better developer experience is top of mind.
